apiVersion: v1
kind: Service
metadata:
  name: api-antony
  namespace: antony
  labels:
    app.kubernetes.io/instance: api-antony
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-antony
    app.kubernetes.io/version: latest
    helm.sh/chart: api-antony-0.1.0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app.kubernetes.io/instance: api-antony
    app.kubernetes.io/name: api-antony
  type: ClusterIP
  sessionAffinity: None